name = input("Enter your name: ")
print("Hello "+name+"! Welcome to the world!")
print()
print("#  #       #  #        #")
print("#  #       #  #        #")
print("#  #       #  #        #")
print("####  ##   #  #   ##   #")
print("#  # ####  #  #  #  #  #")
print("#  # #     #  #  #  #   ")
print("#  #  ###   #  #  ##   #")
print()
print(":D")